class type _identifier = object
    method text: string
end [@bs]

type identifier = _identifier Js.t


module SyntaxKind = struct
    type t =
        | Unknown
        | EndOfFileToken
        | SingleLineCommentTrivia
        | MultiLineCommentTrivia
        | NewLineTrivia
        | WhitespaceTrivia
        | ShebangTrivia
        | ConflictMarkerTrivia
        | NumericLiteral
        | StringLiteral
        | JsxText
        | RegularExpressionLiteral
        | NoSubstitutionTemplateLiteral
        | TemplateHead
        | TemplateMiddle
        | TemplateTail
        | OpenBraceToken
        | CloseBraceToken
        | OpenParenToken
        | CloseParenToken
        | OpenBracketToken
        | CloseBracketToken
        | DotToken
        | DotDotDotToken
        | SemicolonToken
        | CommaToken
        | LessThanToken
        | LessThanSlashToken
        | GreaterThanToken
        | LessThanEqualsToken
        | GreaterThanEqualsToken
        | EqualsEqualsToken
        | ExclamationEqualsToken
        | EqualsEqualsEqualsToken
        | ExclamationEqualsEqualsToken
        | EqualsGreaterThanToken
        | PlusToken
        | MinusToken
        | AsteriskToken
        | AsteriskAsteriskToken
        | SlashToken
        | PercentToken
        | PlusPlusToken
        | MinusMinusToken
        | LessThanLessThanToken
        | GreaterThanGreaterThanToken
        | GreaterThanGreaterThanGreaterThanToken
        | AmpersandToken
        | BarToken
        | CaretToken
        | ExclamationToken
        | TildeToken
        | AmpersandAmpersandToken
        | BarBarToken
        | QuestionToken
        | ColonToken
        | AtToken
        | EqualsToken
        | PlusEqualsToken
        | MinusEqualsToken
        | AsteriskEqualsToken
        | AsteriskAsteriskEqualsToken
        | SlashEqualsToken
        | PercentEqualsToken
        | LessThanLessThanEqualsToken
        | GreaterThanGreaterThanEqualsToken
        | GreaterThanGreaterThanGreaterThanEqualsToken
        | AmpersandEqualsToken
        | BarEqualsToken
        | CaretEqualsToken
        | Identifier
        | BreakKeyword
        | CaseKeyword
        | CatchKeyword
        | ClassKeyword
        | ConstKeyword
        | ContinueKeyword
        | DebuggerKeyword
        | DefaultKeyword
        | DeleteKeyword
        | DoKeyword
        | ElseKeyword
        | EnumKeyword
        | ExportKeyword
        | ExtendsKeyword
        | FalseKeyword
        | FinallyKeyword
        | ForKeyword
        | FunctionKeyword
        | IfKeyword
        | ImportKeyword
        | InKeyword
        | InstanceOfKeyword
        | NewKeyword
        | NullKeyword
        | ReturnKeyword
        | SuperKeyword
        | SwitchKeyword
        | ThisKeyword
        | ThrowKeyword
        | TrueKeyword
        | TryKeyword
        | TypeOfKeyword
        | VarKeyword
        | VoidKeyword
        | WhileKeyword
        | WithKeyword
        | ImplementsKeyword
        | InterfaceKeyword
        | LetKeyword
        | PackageKeyword
        | PrivateKeyword
        | ProtectedKeyword
        | PublicKeyword
        | StaticKeyword
        | YieldKeyword
        | AbstractKeyword
        | AsKeyword
        | AnyKeyword
        | AsyncKeyword
        | AwaitKeyword
        | BooleanKeyword
        | ConstructorKeyword
        | DeclareKeyword
        | GetKeyword
        | IsKeyword
        | KeyOfKeyword
        | ModuleKeyword
        | NamespaceKeyword
        | NeverKeyword
        | ReadonlyKeyword
        | RequireKeyword
        | NumberKeyword
        | SetKeyword
        | StringKeyword
        | SymbolKeyword
        | TypeKeyword
        | UndefinedKeyword
        | FromKeyword
        | GlobalKeyword
        | OfKeyword
        | QualifiedName
        | ComputedPropertyName
        | TypeParameter
        | Parameter
        | Decorator
        | PropertySignature
        | PropertyDeclaration
        | MethodSignature
        | MethodDeclaration
        | Constructor
        | GetAccessor
        | SetAccessor
        | CallSignature
        | ConstructSignature
        | IndexSignature
        | TypePredicate
        | TypeReference
        | FunctionType
        | ConstructorType
        | TypeQuery
        | TypeLiteral
        | ArrayType
        | TupleType
        | UnionType
        | IntersectionType
        | ParenthesizedType
        | ThisType
        | TypeOperator
        | IndexedAccessType
        | MappedType
        | LiteralType
        | ObjectBindingPattern
        | ArrayBindingPattern
        | BindingElement
        | ArrayLiteralExpression
        | ObjectLiteralExpression
        | PropertyAccessExpression
        | ElementAccessExpression
        | CallExpression
        | NewExpression
        | TaggedTemplateExpression
        | TypeAssertionExpression
        | ParenthesizedExpression
        | FunctionExpression
        | ArrowFunction
        | DeleteExpression
        | TypeOfExpression
        | VoidExpression
        | AwaitExpression
        | PrefixUnaryExpression
        | PostfixUnaryExpression
        | BinaryExpression
        | ConditionalExpression
        | TemplateExpression
        | YieldExpression
        | SpreadElement
        | ClassExpression
        | OmittedExpression
        | ExpressionWithTypeArguments
        | AsExpression
        | NonNullExpression
        | MetaProperty
        | TemplateSpan
        | SemicolonClassElement
        | Block
        | VariableStatement
        | EmptyStatement
        | ExpressionStatement
        | IfStatement
        | DoStatement
        | WhileStatement
        | ForStatement
        | ForInStatement
        | ForOfStatement
        | ContinueStatement
        | BreakStatement
        | ReturnStatement
        | WithStatement
        | SwitchStatement
        | LabeledStatement
        | ThrowStatement
        | TryStatement
        | DebuggerStatement
        | VariableDeclaration
        | VariableDeclarationList
        | FunctionDeclaration
        | ClassDeclaration
        | InterfaceDeclaration
        | TypeAliasDeclaration
        | EnumDeclaration
        | ModuleDeclaration
        | ModuleBlock
        | CaseBlock
        | NamespaceExportDeclaration
        | ImportEqualsDeclaration
        | ImportDeclaration
        | ImportClause
        | NamespaceImport
        | NamedImports
        | ImportSpecifier
        | ExportAssignment
        | ExportDeclaration
        | NamedExports
        | ExportSpecifier
        | MissingDeclaration
        | ExternalModuleReference
        | JsxElement
        | JsxSelfClosingElement
        | JsxOpeningElement
        | JsxClosingElement
        | JsxAttribute
        | JsxSpreadAttribute
        | JsxExpression
        | CaseClause
        | DefaultClause
        | HeritageClause
        | CatchClause
        | PropertyAssignment
        | ShorthandPropertyAssignment
        | SpreadAssignment
        | EnumMember
        | SourceFile
        | JSDocTypeExpression
        | JSDocAllType
        | JSDocUnknownType
        | JSDocArrayType
        | JSDocUnionType
        | JSDocTupleType
        | JSDocNullableType
        | JSDocNonNullableType
        | JSDocRecordType
        | JSDocRecordMember
        | JSDocTypeReference
        | JSDocOptionalType
        | JSDocFunctionType
        | JSDocVariadicType
        | JSDocConstructorType
        | JSDocThisType
        | JSDocComment
        | JSDocTag
        | JSDocAugmentsTag
        | JSDocParameterTag
        | JSDocReturnTag
        | JSDocTypeTag
        | JSDocTemplateTag
        | JSDocTypedefTag
        | JSDocPropertyTag
        | JSDocTypeLiteral
        | JSDocLiteralType
        | JSDocNullKeyword
        | JSDocUndefinedKeyword
        | JSDocNeverKeyword
        | SyntaxList
        | NotEmittedStatement
        | PartiallyEmittedExpression
        | MergeDeclarationMarker
        | EndOfDeclarationMarker
        | Count
        | FirstAssignment
        | LastAssignment
        | FirstCompoundAssignment
        | LastCompoundAssignment
        | FirstReservedWord
        | LastReservedWord
        | FirstKeyword
        | LastKeyword
        | FirstFutureReservedWord
        | LastFutureReservedWord
        | FirstTypeNode
        | LastTypeNode
        | FirstPunctuation
        | LastPunctuation
        | FirstToken
        | LastToken
        | FirstTriviaToken
        | LastTriviaToken
        | FirstLiteralToken
        | LastLiteralToken
        | FirstTemplateToken
        | LastTemplateToken
        | FirstBinaryOperator
        | LastBinaryOperator
        | FirstNode
        | FirstJSDocNode
        | LastJSDocNode
        | FirstJSDocTagNode
        | LastJSDocTagNode
    type rawEnum
    external enum : rawEnum = "SyntaxKind" [@@bs.module "typescript"] [@@bs.val]
    external _getName : rawEnum -> t -> string = "" [@@bs.get_index]
    let getName tv = _getName enum tv
end


class type _node = object
    method kind: SyntaxKind.t
    method members: _node Js.t array Js.Undefined.t
    method name: identifier
end [@bs]

type node = _node Js.t

class type _sourceFileObject = object
  method text: string
  method statements: node array
end [@bs]

type sourceFileObject = _sourceFileObject Js.t
external createSourceFile :
  string -> string -> int-> bool -> sourceFileObject =
  "createSourceFile" [@@bs.module "typescript"]
